[build]
    base = "frontend/"
    publish = "build/"

[context.branch-deploy]
    command = "yarn build"
    environment = { REACT_APP_USE_SHEET = "true", REACT_APP_COUNTRY_DATA_SHEET="18kNssP6H4GjGoK0C9K2L-B3UWq74R7R_rWvj9b4iOV0", REACT_APP_META_DATA_SHEET="1HZnH-5_1eEiVrWDxcZPjqYBghkPhDIUFbaqZaGj7OJo" }
[context.production]
    command = "node fetch-data.js && yarn build"
    environment = { REACT_APP_COUNTRY_DATA_SHEET="1Kgaf_opjQ2DNBa_4FdAPo8OE7CFssd_KRM-sEtPCZyE", REACT_APP_META_DATA_SHEET="1WRBebU42GBOLFkMKFAiVCc5HxeBqOmU3UEIKdrf4SCY" }